using System.Text.Json;
using System.Linq;

// initialize the ASP.NET Core Minimal API builder
var builder = WebApplication.CreateBuilder(args);

// configure CORS to allow the React frontend (Vite) to communicate with this API
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowReact", policy =>
    {
        // Allow localhost for local dev, AND any Vercel deployment for production
        policy.SetIsOriginAllowed(origin => 
            new Uri(origin).Host == "localhost" || 
            origin.EndsWith(".vercel.app") // Allows all Vercel preview and production URLs
        )
        .AllowAnyHeader()
        .AllowAnyMethod();
    });
});

var app = builder.Build();

// apply middleware: enable CORS and serve static files from the wwwroot folder
app.UseCors("AllowReact");
app.UseStaticFiles();

// REST API endpoint: GET /api/sustainability/{brand}
app.MapGet("/api/sustainability/{brand}", async (string brand, IWebHostEnvironment env) =>
{
    // locate the data.json file generated by the Python scraper
    var filePath = Path.Combine(env.WebRootPath, "data.json");
    if (!File.Exists(filePath))
    {
        return Results.NotFound(new { error = "Data file not found. Run the Python scraper first." });
    }

    // read and deserialize the JSON file into a list of BrandData objects
    var json = await File.ReadAllTextAsync(filePath);
    
    // propertyNameCaseInsensitive bridges the gap between C# PascalCase and JSON camelCase
    var options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
    var brands = JsonSerializer.Deserialize<List<BrandData>>(json, options);

    // perform a case-insensitive search for the requested brand
    var result = brands?.FirstOrDefault(b => b.Brand.Equals(brand, StringComparison.OrdinalIgnoreCase));

    // return the brand data if found, otherwise return a 404 error
    return result != null ? Results.Ok(result) : Results.NotFound(new { error = "Brand not found." });
});

// start the API server
app.Run();

// data model representing the structure of the sustainability JSON payload
public class BrandData
{
    public string Brand { get; set; } = "";
    public int SustainabilityScore { get; set; }
    public Dictionary<string, int> Materials { get; set; } = new(); // Material composition percentages
    public string LaborPractices { get; set; } = "";
    public List<string> Alternatives { get; set; } = new();
    
    // transparency and fallback fields injected by the Python scraper
    public string? ScrapeStatus { get; set; }
    public string? DataNote { get; set; }
    public string? SourceUrl { get; set; }
    public Dictionary<string, int>? RealSignalsDetected { get; set; }
}