using System.Text.Json;
using System.Linq;
using System.Text.RegularExpressions;

// initialize the ASP.NET Core Minimal API builder
var builder = WebApplication.CreateBuilder(args);

// configure CORS to allow the React frontend (Vite) to communicate with this API
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowReact", policy =>
    {
        // Allow localhost for local dev, AND any Vercel deployment for production
        policy.SetIsOriginAllowed(origin => 
            new Uri(origin).Host == "localhost" || 
            origin.EndsWith(".vercel.app") // Allows all Vercel preview and production URLs
        )
        .AllowAnyHeader()
        .AllowAnyMethod();
    });
});

var app = builder.Build();

// apply middleware: enable CORS and serve static files from the wwwroot folder
app.UseCors("AllowReact");
app.UseStaticFiles();

// REST API endpoint: GET /api/sustainability/{brand}
app.MapGet("/api/sustainability/{brand}", async (string brand, IWebHostEnvironment env) =>
{
    // locate the data.json file generated by the Python scraper
    var filePath = Path.Combine(env.WebRootPath, "data.json");
    if (!File.Exists(filePath))
    {
        return Results.NotFound(new { error = "Data file not found. Run the Python scraper first." });
    }

    // read and deserialize the JSON file into a list of BrandData objects
    var json = await File.ReadAllTextAsync(filePath);
    
    // propertyNameCaseInsensitive bridges the gap between C# PascalCase and JSON camelCase
    var options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
    var brands = JsonSerializer.Deserialize<List<BrandData>>(json, options);

    // perform a case-insensitive search for the requested brand
    var result = brands?.FirstOrDefault(b => b.Brand.Equals(brand, StringComparison.OrdinalIgnoreCase));

    // return the brand data if found, otherwise return a 404 error
    return result != null ? Results.Ok(result) : Results.NotFound(new { error = "Brand not found." });
});

// NEW: Real-time custom URL analyzer endpoint
app.MapPost("/api/sustainability/analyze-url", async (CustomUrlRequest request) =>
{
    if (string.IsNullOrWhiteSpace(request.Url) || !Uri.IsWellFormedUriString(request.Url, UriKind.Absolute))
    {
        return Results.BadRequest(new { error = "Please provide a valid URL." });
    }

    try
    {
        using var httpClient = new HttpClient();
        httpClient.DefaultRequestHeaders.Add("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36");
        
        // fetch the HTML
        var html = await httpClient.GetStringAsync(request.Url);
        
        // parse and clean the HTML (replicating BeautifulSoup)
        var htmlDoc = new HtmlAgilityPack.HtmlDocument();
        htmlDoc.LoadHtml(html);
        
        // remove scripts styles and nav to get clean text
        htmlDoc.DocumentNode.Descendants()
            .Where(n => n.Name == "script" || n.Name == "style" || n.Name == "nav" || n.Name == "footer")
            .ToList()
            .ForEach(n => n.Remove());

        var text = htmlDoc.DocumentNode.InnerText.ToLower();

        // heuristic scoring logic (mirrors the Python scraper)
        var positiveKeywords = new[] { "organic", "recycled", "fair trade", "carbon neutral", "sustainable", "transparent" };
        var negativeKeywords = new[] { "fast fashion", "conventional" };

        int positiveCount = positiveKeywords.Count(kw => Regex.Matches(text, $@"\b{kw}\b").Count > 0);
        int negativeCount = negativeKeywords.Count(kw => Regex.Matches(text, $@"\b{kw}\b").Count > 0);

        int score = 50 + (positiveCount * 3) - (negativeCount * 5);
        score = Math.Max(0, Math.Min(100, score)); // Clamp 0-100

        // build a dynamic response
        var result = new
        {
            Brand = "Custom URL Analysis",
            SustainabilityScore = score,
            Materials = new Dictionary<string, int> { { "analysis_based", 100 } },
            LaborPractices = score >= 70 ? "Positive sustainability indicators detected." : "Standard industry practices.",
            Alternatives = new List<string> { "Pact", "Allbirds", "Tentree" },
            ScrapeStatus = "LIVE_ON_DEMAND",
            DataNote = $"Real-time analysis of provided URL. Score based on keyword density.",
            SourceUrl = request.Url,
            RealSignalsDetected = new Dictionary<string, int> 
            { 
                { "positive_indicators", positiveCount }, 
                { "negative_indicators", negativeCount } 
            }
        };

        return Results.Ok(result);
    }
    catch (Exception ex)
    {
        return Results.BadRequest(new { error = $"Failed to analyze URL: {ex.Message}" });
    }
});


app.Run();



// helper class for the POST request
public class CustomUrlRequest
{
    public string Url { get; set; } = "";
}

// data model representing the structure of the sustainability JSON payload
public class BrandData
{
    public string Brand { get; set; } = "";
    public int SustainabilityScore { get; set; }
    public Dictionary<string, int> Materials { get; set; } = new(); // Material composition percentages
    public string LaborPractices { get; set; } = "";
    public List<string> Alternatives { get; set; } = new();
    
    // transparency and fallback fields injected by the Python scraper
    public string? ScrapeStatus { get; set; }
    public string? DataNote { get; set; }
    public string? SourceUrl { get; set; }
    public Dictionary<string, int>? RealSignalsDetected { get; set; }
}